/*
 * Decompiled by CFR-JS 0.4.0.
 */
final class clb {
    static int field_a;

    public final String toString() {
        throw new IllegalStateException();
    }

    final static ij a(int param0) {
        ij var1 = null;
        var1 = new ij();
        var1.b(-10258, new skb("lo", new Class[]{}, "Say hello"));
        var1.b(-10258, new ogb("set_lag", new Class[]{Integer.TYPE, Integer.TYPE, Integer.TYPE, Integer.TYPE}, (String) null));
        var1.b(param0 + -10274, new jd("set_lag", new Class[]{Integer.TYPE, Integer.TYPE}, (String) null));
        var1.b(-10258, new mva("get_lag_in", new Class[]{}, (String) null));
        var1.b(param0 + -10274, new ala("get_lag_out", new Class[]{}, (String) null));
        var1.b(-10258, new klb("get_lag_standard_deviation_in", new Class[]{}, (String) null));
        var1.b(-10258, new cka("get_lag_standard_deviation_out", new Class[]{}, (String) null));
        var1.b(-10258, new pka("print_settings", new Class[]{}, (String) null));
        var1.b(-10258, new wda("load_settings", new Class[]{String.class}, (String) null));
        var1.b(-10258, new wnb("load_blackbox_recording", new Class[]{Integer.TYPE}, (String) null));
        var1.b(-10258, new dpa("request_newest_blackbox_recording", new Class[]{}, (String) null));
        var1.b(-10258, new eq("set_carousel_constant", new Class[]{String.class}, (String) null));
        var1.b(-10258, new heb("set_serverinfo_votestate", new Class[]{Integer.TYPE, Integer.TYPE}, (String) null));
        var1.b(param0 ^ -10242, new ofb("set_serverinfo_componentstate", new Class[]{Integer.TYPE, Integer.TYPE}, (String) null));
        var1.b(-10258, new uqa("get_loading_missions", new Class[]{}, (String) null));
        var1.b(-10258, new lab("set_loading_missions", new Class[]{Boolean.TYPE}, (String) null));
        var1.b(param0 ^ -10242, new taa("get_trap_mouse", new Class[]{}, (String) null));
        var1.b(-10258, new gq("set_trap_mouse", new Class[]{Boolean.TYPE}, (String) null));
        var1.b(-10258, new tca("get_tab_for_scores", new Class[]{}, (String) null));
        var1.b(-10258, new wg("set_tab_for_scores", new Class[]{Boolean.TYPE}, (String) null));
        var1.b(-10258, new cg("get_toggled_scoreboard", new Class[]{}, (String) null));
        var1.b(-10258, new hca("set_toggled_scoreboard", new Class[]{Boolean.TYPE}, (String) null));
        var1.b(-10258, new og("get_debris_group_colour", new Class[]{}, (String) null));
        var1.b(-10258, new ck("set_debris_group_colour", new Class[]{Boolean.TYPE}, (String) null));
        var1.b(-10258, new rra("get_ship_direction_arrow", new Class[]{}, (String) null));
        var1.b(-10258, new ema("set_ship_direction_arrow", new Class[]{Boolean.TYPE}, (String) null));
        var1.b(-10258, new gaa("get_ship_aim_lines", new Class[]{}, (String) null));
        var1.b(-10258, new awa("set_ship_aim_lines", new Class[]{Boolean.TYPE}, (String) null));
        var1.b(-10258, new dfb("get_allow_ship_saving", new Class[]{}, (String) null));
        var1.b(-10258, new lk("set_allow_ship_saving", new Class[]{Boolean.TYPE}, (String) null));
        var1.b(param0 ^ -10242, new poa("get_use_offscreen_rendering", new Class[]{}, (String) null));
        var1.b(-10258, new jrb("set_use_offscreen_rendering", new Class[]{Boolean.TYPE}, (String) null));
        var1.b(param0 + -10274, new eja("get_use_circle_fill", new Class[]{}, (String) null));
        var1.b(-10258, new jfb("set_use_circle_fill", new Class[]{Boolean.TYPE}, (String) null));
        var1.b(-10258, new baa("get_use_circle_outline", new Class[]{}, (String) null));
        var1.b(param0 ^ -10242, new nha("set_use_circle_outline", new Class[]{Boolean.TYPE}, (String) null));
        var1.b(-10258, new vea("get_use_lines", new Class[]{}, (String) null));
        var1.b(-10258, new ltb("set_use_lines", new Class[]{Boolean.TYPE}, (String) null));
        var1.b(-10258, new apa("get_use_rect_fill", new Class[]{}, (String) null));
        var1.b(-10258, new vha("set_use_rect_fill", new Class[]{Boolean.TYPE}, (String) null));
        var1.b(-10258, new rl("get_use_rect_outline", new Class[]{}, (String) null));
        var1.b(-10258, new mdb("set_use_rect_outline", new Class[]{Boolean.TYPE}, (String) null));
        var1.b(param0 ^ -10242, new fu("get_use_tri_fill", new Class[]{}, (String) null));
        var1.b(-10258, new hjb("set_use_tri_fill", new Class[]{Boolean.TYPE}, (String) null));
        var1.b(-10258, new oja("get_use_polygon_fill", new Class[]{}, (String) null));
        var1.b(param0 + -10274, new eqa("set_use_polygon_fill", new Class[]{Boolean.TYPE}, (String) null));
        var1.b(param0 ^ -10242, new aob("get_show_tutorial", new Class[]{}, (String) null));
        var1.b(-10258, new hha("set_show_tutorial", new Class[]{Boolean.TYPE}, (String) null));
        var1.b(param0 ^ -10242, new scb("get_fps", new Class[]{}, (String) null));
        var1.b(-10258, new op("set_fps", new Class[]{Integer.TYPE}, (String) null));
        var1.b(param0 + -10274, new nob("get_radial_menu_radius", new Class[]{}, (String) null));
        var1.b(param0 ^ -10242, new uba("set_radial_menu_radius", new Class[]{Integer.TYPE}, (String) null));
        var1.b(-10258, new nw("get_minimap_width", new Class[]{}, (String) null));
        var1.b(-10258, new kdb("set_minimap_width", new Class[]{Integer.TYPE}, (String) null));
        var1.b(param0 ^ -10242, new ddb("get_minimap_height", new Class[]{}, (String) null));
        var1.b(-10258, new ppa("set_minimap_height", new Class[]{Integer.TYPE}, (String) null));
        var1.b(param0 + -10274, new na("get_health_bar_width", new Class[]{}, (String) null));
        var1.b(-10258, new bdb("set_health_bar_width", new Class[]{Integer.TYPE}, (String) null));
        var1.b(-10258, new ld("get_health_bar_height", new Class[]{}, (String) null));
        var1.b(-10258, new uka("set_health_bar_height", new Class[]{Integer.TYPE}, (String) null));
        var1.b(-10258, new fq("get_reload_bar_width", new Class[]{}, (String) null));
        var1.b(-10258, new vba("set_reload_bar_width", new Class[]{Integer.TYPE}, (String) null));
        var1.b(-10258, new qwa("get_reload_bar_height", new Class[]{}, (String) null));
        var1.b(-10258, new inb("set_reload_bar_height", new Class[]{Integer.TYPE}, (String) null));
        var1.b(param0 + -10274, new hqa("get_special_order_bar_x", new Class[]{}, (String) null));
        var1.b(param0 + -10274, new jqa("set_special_order_bar_x", new Class[]{Integer.TYPE}, (String) null));
        var1.b(-10258, new ch("get_special_order_bar_y_offset", new Class[]{}, (String) null));
        var1.b(-10258, new cb("set_special_order_bar_y_offset", new Class[]{Integer.TYPE}, (String) null));
        var1.b(-10258, new pg("get_special_order_box_width", new Class[]{}, (String) null));
        var1.b(-10258, new ao("set_special_order_box_width", new Class[]{Integer.TYPE}, (String) null));
        var1.b(-10258, new ewa("get_special_order_box_height", new Class[]{}, (String) null));
        var1.b(-10258, new kj("set_special_order_box_height", new Class[]{Integer.TYPE}, (String) null));
        var1.b(-10258, new s("get_mission_variables_hud_x", new Class[]{}, (String) null));
        var1.b(-10258, new hpa("set_mission_variables_hud_x", new Class[]{Integer.TYPE}, (String) null));
        var1.b(param0 + -10274, new fv("get_mission_variables_hud_y", new Class[]{}, (String) null));
        var1.b(-10258, new msb("set_mission_variables_hud_y", new Class[]{Integer.TYPE}, (String) null));
        var1.b(-10258, new sla("get_audio_range_cutoff", new Class[]{}, (String) null));
        var1.b(-10258, new tsb("set_audio_range_cutoff", new Class[]{Integer.TYPE}, (String) null));
        var1.b(param0 ^ -10242, new qf("get_reverb_gain", new Class[]{}, (String) null));
        var1.b(-10258, new isa("set_reverb_gain", new Class[]{Float.TYPE}, (String) null));
        var1.b(-10258, new ugb("get_reverb_feedback", new Class[]{}, (String) null));
        var1.b(-10258, new ji("set_reverb_feedback", new Class[]{Float.TYPE}, (String) null));
        var1.b(-10258, new lf("get_reverb_damp", new Class[]{}, (String) null));
        var1.b(-10258, new bsa("set_reverb_damp", new Class[]{Float.TYPE}, (String) null));
        var1.b(param0 + -10274, new oha("get_reverb_wet", new Class[]{}, (String) null));
        var1.b(-10258, new nh("set_reverb_wet", new Class[]{Float.TYPE}, (String) null));
        var1.b(param0 + -10274, new wq("get_reverb_dry", new Class[]{}, (String) null));
        var1.b(-10258, new jia("set_reverb_dry", new Class[]{Float.TYPE}, (String) null));
        var1.b(-10258, new hra("get_reverb_width", new Class[]{}, (String) null));
        var1.b(-10258, new ui("set_reverb_width", new Class[]{Float.TYPE}, (String) null));
        var1.b(-10258, new kaa("get_blueprint_save_time", new Class[]{}, (String) null));
        var1.b(param0 ^ -10242, new wpb("set_blueprint_save_time", new Class[]{Integer.TYPE}, (String) null));
        var1.b(-10258, new k("get_message_maxage", new Class[]{}, (String) null));
        var1.b(-10258, new hhb("set_message_maxage", new Class[]{Integer.TYPE}, (String) null));
        var1.b(-10258, new bg("get_message_fadetime", new Class[]{}, (String) null));
        var1.b(param0 + -10274, new aj("set_message_fadetime", new Class[]{Integer.TYPE}, (String) null));
        var1.b(-10258, new edb("get_message_max", new Class[]{}, (String) null));
        var1.b(param0 + -10274, new ueb("set_message_max", new Class[]{Integer.TYPE}, (String) null));
        var1.b(param0 ^ -10242, new sp("get_ondamage_particle_speed", new Class[]{}, (String) null));
        var1.b(-10258, new vbb("set_ondamage_particle_speed", new Class[]{Integer.TYPE}, (String) null));
        var1.b(-10258, new ufa("get_ondamage_particle_life", new Class[]{}, (String) null));
        var1.b(-10258, new rsa("set_ondamage_particle_life", new Class[]{Integer.TYPE}, (String) null));
        var1.b(param0 ^ -10242, new vua("get_ondamage_particle_fadestart", new Class[]{}, (String) null));
        var1.b(param0 ^ -10242, new uo("set_ondamage_particle_fadestart", new Class[]{Integer.TYPE}, (String) null));
        var1.b(-10258, new kna("get_shields_directional_halfarc_cuts", new Class[]{}, (String) null));
        var1.b(-10258, new gjb("set_shields_directional_halfarc_cuts", new Class[]{Integer.TYPE}, (String) null));
        var1.b(param0 + -10274, new gp("get_shields_directional_arc_particle_life", new Class[]{}, (String) null));
        var1.b(-10258, new urb("set_shields_directional_arc_particle_life", new Class[]{Integer.TYPE}, (String) null));
        var1.b(-10258, new cga("get_shields_directional_arc_particle_speed_downshift", new Class[]{}, (String) null));
        var1.b(param0 ^ -10242, new tg("set_shields_directional_arc_particle_speed_downshift", new Class[]{Integer.TYPE}, (String) null));
        var1.b(-10258, new pt("get_auto_afk_timeout", new Class[]{}, (String) null));
        var1.b(-10258, new mla("set_auto_afk_timeout", new Class[]{Integer.TYPE}, (String) null));
        var1.b(-10258, new rqb("get_test_action_lag", new Class[]{}, (String) null));
        var1.b(-10258, new tmb("set_test_action_lag", new Class[]{Integer.TYPE}, (String) null));
        var1.b(-10258, new kfb("get_build_view_autozoom", new Class[]{}, (String) null));
        var1.b(param0 + -10274, new vkb("set_build_view_autozoom", new Class[]{Integer.TYPE}, (String) null));
        var1.b(-10258, new ur("get_build_view_autozoom_timeout", new Class[]{}, (String) null));
        var1.b(-10258, new mh("set_build_view_autozoom_timeout", new Class[]{Integer.TYPE}, (String) null));
        var1.b(-10258, new eo("get_build_view_autozoom_end_on_action", new Class[]{}, (String) null));
        var1.b(-10258, new rkb("set_build_view_autozoom_end_on_action", new Class[]{Integer.TYPE}, (String) null));
        var1.b(-10258, new fc("get_num_stars", new Class[]{}, (String) null));
        var1.b(-10258, new kq("set_num_stars", new Class[]{Integer.TYPE}, (String) null));
        var1.b(param0 ^ -10242, new srb("get_use_bloom", new Class[]{}, (String) null));
        var1.b(-10258, new gja("set_use_bloom", new Class[]{Integer.TYPE}, (String) null));
        var1.b(-10258, new ki("get_use_sprites", new Class[]{}, (String) null));
        var1.b(-10258, new wab("set_use_sprites", new Class[]{Integer.TYPE}, (String) null));
        var1.b(param0 + -10274, new oc("get_use_background", new Class[]{}, (String) null));
        var1.b(param0 + -10274, new cw("set_use_background", new Class[]{Integer.TYPE}, (String) null));
        var1.b(-10258, new leb("get_use_background_in_fullscreen", new Class[]{}, (String) null));
        var1.b(param0 + -10274, new jda("set_use_background_in_fullscreen", new Class[]{Integer.TYPE}, (String) null));
        var1.b(-10258, new fea("get_use_extra_background", new Class[]{}, (String) null));
        var1.b(-10258, new gcb("set_use_extra_background", new Class[]{Integer.TYPE}, (String) null));
        var1.b(param0 + -10274, new cab("get_use_nice_trails", new Class[]{}, (String) null));
        var1.b(-10258, new eba("set_use_nice_trails", new Class[]{Integer.TYPE}, (String) null));
        var1.b(param0 ^ -10242, new iba("get_auto_detail", new Class[]{}, (String) null));
        var1.b(-10258, new kcb("set_auto_detail", new Class[]{Integer.TYPE}, (String) null));
        var1.b(-10258, new fha("get_debug_line_life", new Class[]{}, (String) null));
        var1.b(-10258, new ca("set_debug_line_life", new Class[]{Integer.TYPE}, (String) null));
        var1.b(-10258, new lba("get_use_filled_polygons", new Class[]{}, (String) null));
        var1.b(param0 + -10274, new trb("set_use_filled_polygons", new Class[]{Integer.TYPE}, (String) null));
        var1.b(-10258, new pk("get_use_detail_lines", new Class[]{}, (String) null));
        var1.b(param0 ^ -10242, new icb("set_use_detail_lines", new Class[]{Integer.TYPE}, (String) null));
        var1.b(-10258, new erb("get_bloom_threshold_percentage", new Class[]{}, (String) null));
        var1.b(-10258, new uib("set_bloom_threshold_percentage", new Class[]{Integer.TYPE}, (String) null));
        var1.b(-10258, new pp("get_bloom_coefficient_percentage", new Class[]{}, (String) null));
        var1.b(-10258, new kk("set_bloom_coefficient_percentage", new Class[]{Integer.TYPE}, (String) null));
        var1.b(-10258, new jqb("get_autozoom_speed_divide", new Class[]{}, (String) null));
        var1.b(-10258, new qi("set_autozoom_speed_divide", new Class[]{Integer.TYPE}, (String) null));
        var1.b(-10258, new ff("get_autozoom_amount_multiply", new Class[]{}, (String) null));
        var1.b(-10258, new ws("set_autozoom_amount_multiply", new Class[]{Float.TYPE}, (String) null));
        var1.b(-10258, new te("get_nebula_proximity_fade_downshift", new Class[]{}, (String) null));
        var1.b(-10258, new pcb("set_nebula_proximity_fade_downshift", new Class[]{Integer.TYPE}, (String) null));
        var1.b(-10258, new ql("get_use_trails", new Class[]{}, (String) null));
        var1.b(-10258, new mja("set_use_trails", new Class[]{Integer.TYPE}, (String) null));
        var1.b(-10258, new eib("get_fighter_vision", new Class[]{}, (String) null));
        var1.b(param0 ^ -10242, new dc("set_fighter_vision", new Class[]{Integer.TYPE}, (String) null));
        var1.b(-10258, new nt("get_ship_to_ship_ram_damage", new Class[]{}, (String) null));
        var1.b(-10258, new loa("set_ship_to_ship_ram_damage", new Class[]{Integer.TYPE}, (String) null));
        var1.b(-10258, new ie("get_team_selection_speedup", new Class[]{}, (String) null));
        var1.b(-10258, new dob("set_team_selection_speedup", new Class[]{Integer.TYPE}, (String) null));
        var1.b(-10258, new vc("get_full_mission_set", new Class[]{}, (String) null));
        var1.b(-10258, new sia("set_full_mission_set", new Class[]{Integer.TYPE}, (String) null));
        var1.b(-10258, new kkb("get_wait_for_players", new Class[]{}, (String) null));
        var1.b(-10258, new ica("set_wait_for_players", new Class[]{Integer.TYPE}, (String) null));
        var1.b(-10258, new pha("get_keep_team_colours", new Class[]{}, (String) null));
        if (param0 == 16) {
          var1.b(-10258, new bjb("set_keep_team_colours", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new o("get_debris_collision", new Class[]{}, (String) null));
          var1.b(-10258, new rib("set_debris_collision", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new qta("get_debris_partitioned", new Class[]{}, (String) null));
          var1.b(param0 + -10274, new pba("set_debris_partitioned", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new fla("get_debris_collision_damage", new Class[]{}, (String) null));
          var1.b(-10258, new cmb("set_debris_collision_damage", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new ig("get_debris_projectile_collision", new Class[]{}, (String) null));
          var1.b(-10258, new em("set_debris_projectile_collision", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new nkb("get_debris_throwable", new Class[]{}, (String) null));
          var1.b(-10258, new rfb("set_debris_throwable", new Class[]{Integer.TYPE}, (String) null));
          var1.b(param0 ^ -10242, new opb("get_missiles_hit_source_team", new Class[]{}, (String) null));
          var1.b(param0 ^ -10242, new acb("set_missiles_hit_source_team", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new hsa("get_missiles_damage_source_team", new Class[]{}, (String) null));
          var1.b(-10258, new lib("set_missiles_damage_source_team", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new ll("get_grappling_hooks_damageable_by_source_player", new Class[]{}, (String) null));
          var1.b(-10258, new qo("set_grappling_hooks_damageable_by_source_player", new Class[]{Integer.TYPE}, (String) null));
          var1.b(param0 + -10274, new ru("get_thruster_binding_move_and_turn_has_opposite_move", new Class[]{}, (String) null));
          var1.b(-10258, new df("set_thruster_binding_move_and_turn_has_opposite_move", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new lha("get_nebula_fades_out_when_close", new Class[]{}, (String) null));
          var1.b(-10258, new jab("set_nebula_fades_out_when_close", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new wj("get_debris_found_in_pairs", new Class[]{}, (String) null));
          var1.b(-10258, new uhb("set_debris_found_in_pairs", new Class[]{Integer.TYPE}, (String) null));
          var1.b(param0 ^ -10242, new el("get_fog_of_war_on", new Class[]{}, (String) null));
          var1.b(-10258, new ug("set_fog_of_war_on", new Class[]{Integer.TYPE}, (String) null));
          var1.b(param0 ^ -10242, new pkb("get_use_models", new Class[]{}, (String) null));
          var1.b(param0 ^ -10242, new neb("set_use_models", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new bka("get_innate_thrusters", new Class[]{}, (String) null));
          var1.b(-10258, new hja("set_innate_thrusters", new Class[]{Integer.TYPE}, (String) null));
          var1.b(param0 + -10274, new rwa("get_thruster_autobalancing", new Class[]{}, (String) null));
          var1.b(-10258, new gba("set_thruster_autobalancing", new Class[]{Integer.TYPE}, (String) null));
          var1.b(param0 + -10274, new sab("get_bots", new Class[]{}, (String) null));
          var1.b(param0 ^ -10242, new otb("set_bots", new Class[]{Integer.TYPE}, (String) null));
          var1.b(param0 ^ -10242, new ic("get_detachment_mode", new Class[]{}, (String) null));
          var1.b(-10258, new ve("set_detachment_mode", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new nsa("get_autoaim", new Class[]{}, (String) null));
          var1.b(-10258, new nua("set_autoaim", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new hj("get_salvoaim", new Class[]{}, (String) null));
          var1.b(-10258, new nd("set_salvoaim", new Class[]{Integer.TYPE}, (String) null));
          var1.b(param0 + -10274, new wlb("get_fixedaim", new Class[]{}, (String) null));
          var1.b(-10258, new mgb("set_fixedaim", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new qha("get_angleset", new Class[]{}, (String) null));
          var1.b(-10258, new jr("set_angleset", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new dt("get_salvo_uses_all_energy", new Class[]{}, (String) null));
          var1.b(-10258, new sj("set_salvo_uses_all_energy", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new ina("get_salvo_holdable", new Class[]{}, (String) null));
          var1.b(param0 ^ -10242, new mhb("set_salvo_holdable", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new omb("get_pedros_repair_mode", new Class[]{}, (String) null));
          var1.b(-10258, new oqa("set_pedros_repair_mode", new Class[]{Integer.TYPE}, (String) null));
          var1.b(param0 ^ -10242, new oga("get_pedros_repair_mode_switchtime", new Class[]{}, (String) null));
          var1.b(param0 + -10274, new ria("set_pedros_repair_mode_switchtime", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new lea("get_ship_persistence", new Class[]{}, (String) null));
          var1.b(-10258, new mqa("set_ship_persistence", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new hcb("get_debris_carry_over", new Class[]{}, (String) null));
          var1.b(-10258, new psa("set_debris_carry_over", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new rh("get_debris_carry_over_percentage", new Class[]{}, (String) null));
          var1.b(param0 + -10274, new iua("set_debris_carry_over_percentage", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new rda("get_debris_survives", new Class[]{}, (String) null));
          var1.b(-10258, new jgb("set_debris_survives", new Class[]{Integer.TYPE}, (String) null));
          var1.b(param0 ^ -10242, new mca("get_client_side_dragging", new Class[]{}, (String) null));
          var1.b(-10258, new jl("set_client_side_dragging", new Class[]{Integer.TYPE}, (String) null));
          var1.b(param0 + -10274, new bta("get_salvo_damage_multiplier", new Class[]{}, (String) null));
          var1.b(-10258, new jnb("set_salvo_damage_multiplier", new Class[]{Integer.TYPE}, (String) null));
          var1.b(param0 ^ -10242, new ww("get_salvo_repair_time_multiplier", new Class[]{}, (String) null));
          var1.b(-10258, new fd("set_salvo_repair_time_multiplier", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new ir("get_mp_sandbox_enemy_spawn_limit", new Class[]{}, (String) null));
          var1.b(-10258, new dsb("set_mp_sandbox_enemy_spawn_limit", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new ljb("get_max_ship_size", new Class[]{}, (String) null));
          var1.b(-10258, new mra("set_max_ship_size", new Class[]{Integer.TYPE}, (String) null));
          var1.b(param0 + -10274, new era("get_fighters_per_player_maximum", new Class[]{}, (String) null));
          var1.b(-10258, new fva("set_fighters_per_player_maximum", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new ew("get_burst_fire_max_energy", new Class[]{}, (String) null));
          var1.b(-10258, new mk("set_burst_fire_max_energy", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new prb("get_burst_fire_regeneration_rate", new Class[]{}, (String) null));
          var1.b(param0 + -10274, new qm("set_burst_fire_regeneration_rate", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new gfa("get_burst_fire_reload", new Class[]{}, (String) null));
          var1.b(-10258, new va("set_burst_fire_reload", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new nab("get_ship_spawn_invulnerability_time", new Class[]{}, (String) null));
          var1.b(param0 ^ -10242, new ov("set_ship_spawn_invulnerability_time", new Class[]{Integer.TYPE}, (String) null));
          var1.b(param0 + -10274, new vg("get_fog_of_war_sensor_range", new Class[]{}, (String) null));
          var1.b(-10258, new lqb("set_fog_of_war_sensor_range", new Class[]{Integer.TYPE}, (String) null));
          var1.b(param0 ^ -10242, new sdb("get_thruster_binding_balance_threshold", new Class[]{}, (String) null));
          var1.b(param0 ^ -10242, new cha("set_thruster_binding_balance_threshold", new Class[]{Integer.TYPE}, (String) null));
          var1.b(param0 + -10274, new stb("get_component_breaking_explosion_force_multiplier", new Class[]{}, (String) null));
          var1.b(-10258, new tna("set_component_breaking_explosion_force_multiplier", new Class[]{Integer.TYPE}, (String) null));
          var1.b(param0 + -10274, new fp("get_physics_collision_force_multiplier", new Class[]{}, (String) null));
          var1.b(-10258, new qt("set_physics_collision_force_multiplier", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new nca("get_physics_collision_grappling_hook_force_multiplier", new Class[]{}, (String) null));
          var1.b(-10258, new gt("set_physics_collision_grappling_hook_force_multiplier", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new vgb("get_physics_collision_phantom_force_multiplier", new Class[]{}, (String) null));
          var1.b(param0 ^ -10242, new qja("set_physics_collision_phantom_force_multiplier", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new jna("get_debris_detachment_force_multiplier", new Class[]{}, (String) null));
          var1.b(param0 ^ -10242, new kjb("set_debris_detachment_force_multiplier", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new vnb("get_grapple_debris", new Class[]{}, (String) null));
          var1.b(-10258, new fsa("set_grapple_debris", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new epa("get_debris_grabbing_range", new Class[]{}, (String) null));
          var1.b(-10258, new tfb("set_debris_grabbing_range", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new msa("get_debris_max", new Class[]{}, (String) null));
          var1.b(param0 + -10274, new rka("set_debris_max", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new nr("get_mission_votes", new Class[]{}, (String) null));
          var1.b(-10258, new oba("set_mission_votes", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new hlb("get_mutator_votes", new Class[]{}, (String) null));
          var1.b(-10258, new ieb("set_mutator_votes", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new pra("get_mission_time_limit", new Class[]{}, (String) null));
          var1.b(-10258, new gv("set_mission_time_limit", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new oab("get_armageddon_timer_start", new Class[]{}, (String) null));
          var1.b(-10258, new qla("set_armageddon_timer_start", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new jcb("get_armageddon_warning", new Class[]{}, (String) null));
          var1.b(-10258, new seb("set_armageddon_warning", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new tma("get_armageddon_length", new Class[]{}, (String) null));
          var1.b(-10258, new cca("set_armageddon_length", new Class[]{Integer.TYPE}, (String) null));
          var1.b(param0 ^ -10242, new ls("get_mission_terrain_nebula_probability", new Class[]{}, (String) null));
          var1.b(-10258, new sqa("set_mission_terrain_nebula_probability", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new mtb("get_mission_terrain_asteroid_probability", new Class[]{}, (String) null));
          var1.b(-10258, new unb("set_mission_terrain_asteroid_probability", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new gwa("get_mission_terrain_debris_probability", new Class[]{}, (String) null));
          var1.b(-10258, new nhb("set_mission_terrain_debris_probability", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new tm("get_mission_terrain_space_probability", new Class[]{}, (String) null));
          var1.b(-10258, new ek("set_mission_terrain_space_probability", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new afa("get_mission_terrain_voting_chancestep", new Class[]{}, (String) null));
          var1.b(-10258, new ua("set_mission_terrain_voting_chancestep", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new iga("get_mission_debris_default_probability", new Class[]{}, (String) null));
          var1.b(-10258, new aq("set_mission_debris_default_probability", new Class[]{Integer.TYPE}, (String) null));
          var1.b(param0 + -10274, new dwa("get_mission_debris_voting_chancestep", new Class[]{}, (String) null));
          var1.b(-10258, new uta("set_mission_debris_voting_chancestep", new Class[]{Integer.TYPE}, (String) null));
          var1.b(param0 ^ -10242, new hta("get_resource_node_capture_time", new Class[]{}, (String) null));
          var1.b(-10258, new bfa("set_resource_node_capture_time", new Class[]{Integer.TYPE}, (String) null));
          var1.b(param0 + -10274, new eg("get_mission_resnet_resource_tick_time", new Class[]{}, (String) null));
          var1.b(-10258, new foa("set_mission_resnet_resource_tick_time", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new kh("get_mass_driver_randomness", new Class[]{}, (String) null));
          var1.b(param0 ^ -10242, new aab("set_mass_driver_randomness", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new eda("get_torpedo_randomness", new Class[]{}, (String) null));
          var1.b(-10258, new mrb("set_torpedo_randomness", new Class[]{Integer.TYPE}, (String) null));
          var1.b(param0 ^ -10242, new bo("get_laser_randomness", new Class[]{}, (String) null));
          var1.b(param0 + -10274, new qea("set_laser_randomness", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new ee("get_bomblet_spray_randomness", new Class[]{}, (String) null));
          var1.b(param0 + -10274, new lb("set_bomblet_spray_randomness", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new tab("get_phased_energy_beam_randomness", new Class[]{}, (String) null));
          var1.b(param0 ^ -10242, new emb("set_phased_energy_beam_randomness", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new mpa("get_sniper_cannon_randomness", new Class[]{}, (String) null));
          var1.b(param0 ^ -10242, new fb("set_sniper_cannon_randomness", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new rta("get_missile_launcher_randomness", new Class[]{}, (String) null));
          var1.b(param0 ^ -10242, new iqb("set_missile_launcher_randomness", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new wpa("get_point_defence_laser_randomness", new Class[]{}, (String) null));
          var1.b(-10258, new dhb("set_point_defence_laser_randomness", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new pua("get_countermeasure_launcher_randomness", new Class[]{}, (String) null));
          var1.b(-10258, new aha("set_countermeasure_launcher_randomness", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new eaa("get_mass_driver_projectiles", new Class[]{}, (String) null));
          var1.b(param0 ^ -10242, new vr("set_mass_driver_projectiles", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new vwa("get_laser_projectiles", new Class[]{}, (String) null));
          var1.b(-10258, new bqb("set_laser_projectiles", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new jmb("get_bomblet_spray_projectiles", new Class[]{}, (String) null));
          var1.b(-10258, new ad("set_bomblet_spray_projectiles", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new kga("get_phased_energy_beam_projectiles", new Class[]{}, (String) null));
          var1.b(-10258, new hr("set_phased_energy_beam_projectiles", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new dd("get_torpedo_projectiles", new Class[]{}, (String) null));
          var1.b(-10258, new bm("set_torpedo_projectiles", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new aka("get_sniper_cannon_projectiles", new Class[]{}, (String) null));
          var1.b(-10258, new gra("set_sniper_cannon_projectiles", new Class[]{Integer.TYPE}, (String) null));
          var1.b(param0 ^ -10242, new ama("get_missile_launcher_projectiles", new Class[]{}, (String) null));
          var1.b(-10258, new fqb("set_missile_launcher_projectiles", new Class[]{Integer.TYPE}, (String) null));
          var1.b(param0 ^ -10242, new pqa("get_point_defence_laser_projectiles", new Class[]{}, (String) null));
          var1.b(-10258, new gkb("set_point_defence_laser_projectiles", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new mt("get_countermeasure_launcher_projectiles", new Class[]{}, (String) null));
          var1.b(-10258, new jh("set_countermeasure_launcher_projectiles", new Class[]{Integer.TYPE}, (String) null));
          var1.b(param0 + -10274, new hmb("get_mass_driver_projectile_life", new Class[]{}, "Lifetime of a bullet"));
          var1.b(-10258, new rnb("set_mass_driver_projectile_life", new Class[]{Integer.TYPE}, "Lifetime of a bullet"));
          var1.b(param0 + -10274, new oeb("get_torpedo_projectile_life", new Class[]{}, (String) null));
          var1.b(-10258, new web("set_torpedo_projectile_life", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new eia("get_bomblet_spray_projectile_life", new Class[]{}, (String) null));
          var1.b(-10258, new lna("set_bomblet_spray_projectile_life", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new u("get_sniper_cannon_projectile_life", new Class[]{}, (String) null));
          var1.b(-10258, new qia("set_sniper_cannon_projectile_life", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new jha("get_missile_launcher_projectile_life", new Class[]{}, (String) null));
          var1.b(-10258, new fe("set_missile_launcher_projectile_life", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new keb("get_countermeasure_launcher_projectile_life", new Class[]{}, (String) null));
          var1.b(-10258, new he("set_countermeasure_launcher_projectile_life", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new snb("get_default_firing_leeway", new Class[]{}, (String) null));
          var1.b(-10258, new esa("set_default_firing_leeway", new Class[]{Integer.TYPE}, (String) null));
          var1.b(param0 + -10274, new vi("get_sniper_cannon_firing_leeway", new Class[]{}, (String) null));
          var1.b(-10258, new sga("set_sniper_cannon_firing_leeway", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new vl("get_mass_driver_fire_force", new Class[]{}, (String) null));
          var1.b(-10258, new dua("set_mass_driver_fire_force", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new ke("get_torpedo_fire_force", new Class[]{}, (String) null));
          var1.b(-10258, new mp("set_torpedo_fire_force", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new frb("get_laser_fire_force", new Class[]{}, (String) null));
          var1.b(param0 + -10274, new aua("set_laser_fire_force", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new rja("get_bomblet_spray_fire_force", new Class[]{}, (String) null));
          var1.b(param0 + -10274, new laa("set_bomblet_spray_fire_force", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new lva("get_phased_energy_beam_fire_force", new Class[]{}, (String) null));
          var1.b(-10258, new fqa("set_phased_energy_beam_fire_force", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new su("get_machine_gun_fire_force", new Class[]{}, (String) null));
          var1.b(-10258, new raa("set_machine_gun_fire_force", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new th("get_sniper_cannon_fire_force", new Class[]{}, (String) null));
          var1.b(-10258, new gka("set_sniper_cannon_fire_force", new Class[]{Integer.TYPE}, (String) null));
          var1.b(param0 + -10274, new bj("get_missile_launcher_fire_force", new Class[]{}, (String) null));
          var1.b(-10258, new eha("set_missile_launcher_fire_force", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new nm("get_point_defence_laser_fire_force", new Class[]{}, (String) null));
          var1.b(param0 ^ -10242, new vpb("set_point_defence_laser_fire_force", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new qfb("get_countermeasure_launcher_fire_force", new Class[]{}, (String) null));
          var1.b(-10258, new ra("set_countermeasure_launcher_fire_force", new Class[]{Integer.TYPE}, (String) null));
          var1.b(param0 ^ -10242, new kwa("get_mass_driver_reload", new Class[]{}, (String) null));
          var1.b(-10258, new jea("set_mass_driver_reload", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new noa("get_torpedo_reload", new Class[]{}, (String) null));
          var1.b(-10258, new gsa("set_torpedo_reload", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new ks("get_laser_reload", new Class[]{}, (String) null));
          var1.b(-10258, new dba("set_laser_reload", new Class[]{Integer.TYPE}, (String) null));
          var1.b(param0 + -10274, new js("get_bomblet_spray_reload", new Class[]{}, (String) null));
          var1.b(param0 + -10274, new wd("set_bomblet_spray_reload", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new ena("get_phased_energy_beam_reload", new Class[]{}, (String) null));
          var1.b(-10258, new tk("set_phased_energy_beam_reload", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new wbb("get_machine_gun_reload", new Class[]{}, (String) null));
          var1.b(-10258, new job("set_machine_gun_reload", new Class[]{Integer.TYPE}, (String) null));
          var1.b(param0 ^ -10242, new rd("get_sniper_cannon_reload", new Class[]{}, (String) null));
          var1.b(param0 + -10274, new hba("set_sniper_cannon_reload", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new kn("get_fighter_bay_reload", new Class[]{}, (String) null));
          var1.b(-10258, new pta("set_fighter_bay_reload", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new gk("get_point_defence_laser_reload", new Class[]{}, (String) null));
          var1.b(param0 + -10274, new fua("set_point_defence_laser_reload", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new iv("get_mass_driver_aimspeed", new Class[]{}, (String) null));
          var1.b(-10258, new hib("set_mass_driver_aimspeed", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new hgb("get_torpedo_aimspeed", new Class[]{}, (String) null));
          var1.b(-10258, new wr("set_torpedo_aimspeed", new Class[]{Integer.TYPE}, (String) null));
          var1.b(param0 ^ -10242, new ejb("get_laser_aimspeed", new Class[]{}, (String) null));
          var1.b(-10258, new pqb("set_laser_aimspeed", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new vda("get_fighter_bay_aimspeed", new Class[]{}, (String) null));
          var1.b(param0 + -10274, new up("set_fighter_bay_aimspeed", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new qmb("get_spinning_blade_aimspeed", new Class[]{}, (String) null));
          var1.b(param0 ^ -10242, new ni("set_spinning_blade_aimspeed", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new wrb("get_sniper_cannon_aimspeed", new Class[]{}, (String) null));
          var1.b(-10258, new vt("set_sniper_cannon_aimspeed", new Class[]{Integer.TYPE}, (String) null));
          var1.b(param0 + -10274, new jm("get_bomblet_spray_aimspeed", new Class[]{}, (String) null));
          var1.b(-10258, new rf("set_bomblet_spray_aimspeed", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new pga("get_phased_energy_beam_aimspeed", new Class[]{}, (String) null));
          var1.b(param0 + -10274, new nda("set_phased_energy_beam_aimspeed", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new lr("get_machine_gun_aimspeed", new Class[]{}, (String) null));
          var1.b(-10258, new qv("set_machine_gun_aimspeed", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new pmb("get_grappling_hook_aimspeed", new Class[]{}, (String) null));
          var1.b(-10258, new aga("set_grappling_hook_aimspeed", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new eob("get_missile_launcher_aimspeed", new Class[]{}, (String) null));
          var1.b(-10258, new jhb("set_missile_launcher_aimspeed", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new sbb("get_point_defence_laser_aimspeed", new Class[]{}, (String) null));
          var1.b(-10258, new ph("set_point_defence_laser_aimspeed", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new hs("get_countermeasure_launcher_aimspeed", new Class[]{}, (String) null));
          var1.b(-10258, new dn("set_countermeasure_launcher_aimspeed", new Class[]{Integer.TYPE}, (String) null));
          var1.b(param0 + -10274, new ftb("get_mass_driver_aimarc", new Class[]{}, (String) null));
          var1.b(param0 + -10274, new tnb("set_mass_driver_aimarc", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new usa("get_torpedo_aimarc", new Class[]{}, (String) null));
          var1.b(-10258, new sta("set_torpedo_aimarc", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new ceb("get_laser_aimarc", new Class[]{}, (String) null));
          var1.b(-10258, new qra("set_laser_aimarc", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new po("get_fighter_bay_aimarc", new Class[]{}, (String) null));
          var1.b(-10258, new cra("set_fighter_bay_aimarc", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new mlb("get_spinning_blade_aimarc", new Class[]{}, (String) null));
          var1.b(-10258, new brb("set_spinning_blade_aimarc", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new iva("get_sniper_cannon_aimarc", new Class[]{}, (String) null));
          var1.b(-10258, new dh("set_sniper_cannon_aimarc", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new am("get_bomblet_spray_aimarc", new Class[]{}, (String) null));
          var1.b(param0 ^ -10242, new nlb("set_bomblet_spray_aimarc", new Class[]{Integer.TYPE}, (String) null));
          var1.b(param0 ^ -10242, new plb("get_phased_energy_beam_aimarc", new Class[]{}, (String) null));
          var1.b(param0 + -10274, new pdb("set_phased_energy_beam_aimarc", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new fhb("get_machine_gun_aimarc", new Class[]{}, (String) null));
          var1.b(param0 ^ -10242, new cta("set_machine_gun_aimarc", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new rmb("get_grappling_hook_aimarc", new Class[]{}, (String) null));
          var1.b(-10258, new ahb("set_grappling_hook_aimarc", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new jib("get_missile_launcher_aimarc", new Class[]{}, (String) null));
          var1.b(-10258, new efa("set_missile_launcher_aimarc", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new vaa("get_point_defence_laser_aimarc", new Class[]{}, (String) null));
          var1.b(-10258, new hwa("set_point_defence_laser_aimarc", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new dva("get_countermeasure_launcher_aimarc", new Class[]{}, (String) null));
          var1.b(-10258, new vsa("set_countermeasure_launcher_aimarc", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new vo("get_mass_driver_projectile_damage", new Class[]{}, (String) null));
          var1.b(-10258, new qoa("set_mass_driver_projectile_damage", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new wo("get_torpedo_projectile_damage", new Class[]{}, (String) null));
          var1.b(-10258, new bpb("set_torpedo_projectile_damage", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new kg("get_laser_beam_projectile_damage", new Class[]{}, (String) null));
          var1.b(-10258, new wb("set_laser_beam_projectile_damage", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new eva("get_machine_gun_projectile_damage", new Class[]{}, (String) null));
          var1.b(-10258, new kpa("set_machine_gun_projectile_damage", new Class[]{Integer.TYPE}, (String) null));
          var1.b(param0 + -10274, new sq("get_sniper_cannon_projectile_damage", new Class[]{}, (String) null));
          var1.b(-10258, new we("set_sniper_cannon_projectile_damage", new Class[]{Integer.TYPE}, (String) null));
          var1.b(param0 + -10274, new ioa("get_bomblet_spray_projectile_damage", new Class[]{}, (String) null));
          var1.b(param0 ^ -10242, new pma("set_bomblet_spray_projectile_damage", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new qu("get_explosion_projectile_damage", new Class[]{}, (String) null));
          var1.b(-10258, new hoa("set_explosion_projectile_damage", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new vqb("get_point_defence_laser_projectile_damage", new Class[]{}, (String) null));
          var1.b(-10258, new nia("set_point_defence_laser_projectile_damage", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new lcb("get_point_defence_laser_projectile_intercept_damage", new Class[]{}, (String) null));
          var1.b(-10258, new orb("set_point_defence_laser_projectile_intercept_damage", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new ijb("get_mass_driver_projectile_ondamage_particles", new Class[]{}, (String) null));
          var1.b(-10258, new njb("set_mass_driver_projectile_ondamage_particles", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new bgb("get_torpedo_projectile_ondamage_particles", new Class[]{}, (String) null));
          var1.b(-10258, new wea("set_torpedo_projectile_ondamage_particles", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new sk("get_phased_energy_beam_projectile_ondamage_particles", new Class[]{}, (String) null));
          var1.b(-10258, new lda("set_phased_energy_beam_projectile_ondamage_particles", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new hv("get_sniper_cannon_projectile_ondamage_particles", new Class[]{}, (String) null));
          var1.b(-10258, new ma("set_sniper_cannon_projectile_ondamage_particles", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new ela("get_bomblet_spray_projectile_ondamage_particles", new Class[]{}, (String) null));
          var1.b(-10258, new tqa("set_bomblet_spray_projectile_ondamage_particles", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new gua("get_explosion_projectile_ondamage_particles", new Class[]{}, (String) null));
          var1.b(-10258, new wn("set_explosion_projectile_ondamage_particles", new Class[]{Integer.TYPE}, (String) null));
          var1.b(param0 ^ -10242, new er("get_point_defence_laser_projectile_ondamage_particles", new Class[]{}, (String) null));
          var1.b(-10258, new st("set_point_defence_laser_projectile_ondamage_particles", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new qe("get_mass_driver_energy_used", new Class[]{}, (String) null));
          var1.b(-10258, new gbb("set_mass_driver_energy_used", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new pda("get_torpedo_energy_used", new Class[]{}, (String) null));
          var1.b(-10258, new de("set_torpedo_energy_used", new Class[]{Integer.TYPE}, (String) null));
          var1.b(param0 ^ -10242, new fmb("get_laser_energy_used", new Class[]{}, (String) null));
          var1.b(-10258, new bja("set_laser_energy_used", new Class[]{Integer.TYPE}, (String) null));
          var1.b(param0 ^ -10242, new ip("get_bomblet_spray_energy_used", new Class[]{}, (String) null));
          var1.b(param0 ^ -10242, new maa("set_bomblet_spray_energy_used", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new hfb("get_phased_energy_beam_energy_used", new Class[]{}, (String) null));
          var1.b(-10258, new cu("set_phased_energy_beam_energy_used", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new ag("get_machine_gun_energy_used", new Class[]{}, (String) null));
          var1.b(-10258, new si("set_machine_gun_energy_used", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new egb("get_sniper_cannon_energy_used", new Class[]{}, (String) null));
          var1.b(-10258, new oea("set_sniper_cannon_energy_used", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new nu("get_missile_launcher_energy_used", new Class[]{}, (String) null));
          var1.b(-10258, new jj("set_missile_launcher_energy_used", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new lgb("get_countermeasure_launcher_energy_used", new Class[]{}, (String) null));
          var1.b(-10258, new ega("set_countermeasure_launcher_energy_used", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new gr("get_point_defence_laser_energy_used", new Class[]{}, (String) null));
          var1.b(-10258, new uua("set_point_defence_laser_energy_used", new Class[]{Integer.TYPE}, (String) null));
          var1.b(param0 + -10274, new wra("get_torpedo_acceleration", new Class[]{}, (String) null));
          var1.b(-10258, new ss("set_torpedo_acceleration", new Class[]{Integer.TYPE}, (String) null));
          var1.b(param0 ^ -10242, new irb("get_thruster_force", new Class[]{}, (String) null));
          var1.b(-10258, new sea("set_thruster_force", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new rr("get_thruster_booster_force", new Class[]{}, (String) null));
          var1.b(-10258, new dk("set_thruster_booster_force", new Class[]{Integer.TYPE}, (String) null));
          var1.b(param0 + -10274, new idb("get_thruster_small_force", new Class[]{}, (String) null));
          var1.b(param0 ^ -10242, new ec("set_thruster_small_force", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new ed("get_velocity_sustain", new Class[]{}, (String) null));
          var1.b(param0 + -10274, new qna("set_velocity_sustain", new Class[]{Integer.TYPE}, (String) null));
          var1.b(param0 + -10274, new udb("get_velocity_sustain_max", new Class[]{}, (String) null));
          var1.b(param0 ^ -10242, new hh("set_velocity_sustain_max", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new rua("get_angular_velocity_sustain", new Class[]{}, (String) null));
          var1.b(-10258, new go("set_angular_velocity_sustain", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new ipa("get_thruster_particle_speed_downshift", new Class[]{}, (String) null));
          var1.b(-10258, new ohb("set_thruster_particle_speed_downshift", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new fi("get_thruster_particle_life", new Class[]{}, (String) null));
          var1.b(-10258, new mwa("set_thruster_particle_life", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new uh("get_angular_force_downshift", new Class[]{}, (String) null));
          var1.b(-10258, new knb("set_angular_force_downshift", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new qnb("get_angular_velocity_sustain_max", new Class[]{}, (String) null));
          var1.b(-10258, new qk("set_angular_velocity_sustain_max", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new uaa("get_torque_downshift", new Class[]{}, (String) null));
          var1.b(param0 + -10274, new id("set_torque_downshift", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new ktb("get_moment_of_inertia_predivide_downshift", new Class[]{}, (String) null));
          var1.b(-10258, new vk("set_moment_of_inertia_predivide_downshift", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new gha("get_moment_of_inertia_perpoint_calc_downshift", new Class[]{}, (String) null));
          var1.b(-10258, new tta("set_moment_of_inertia_perpoint_calc_downshift", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new tdb("get_spinning_blade_top_speed", new Class[]{}, (String) null));
          var1.b(-10258, new ula("set_spinning_blade_top_speed", new Class[]{Integer.TYPE}, (String) null));
          var1.b(param0 + -10274, new qib("get_spinning_blade_spinup_speed", new Class[]{}, (String) null));
          var1.b(-10258, new obb("set_spinning_blade_spinup_speed", new Class[]{Integer.TYPE}, (String) null));
          var1.b(param0 + -10274, new jc("get_spinning_blade_spindamage_multiplier", new Class[]{}, (String) null));
          var1.b(-10258, new lqa("set_spinning_blade_spindamage_multiplier", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new fda("get_phased_energy_beam_pulsetime", new Class[]{}, (String) null));
          var1.b(-10258, new ukb("set_phased_energy_beam_pulsetime", new Class[]{Integer.TYPE}, (String) null));
          var1.b(param0 + -10274, new ju("get_phased_energy_beam_pulse_fadetime", new Class[]{}, (String) null));
          var1.b(-10258, new itb("set_phased_energy_beam_pulse_fadetime", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new paa("get_machine_gun_pulsetime", new Class[]{}, (String) null));
          var1.b(param0 ^ -10242, new iha("set_machine_gun_pulsetime", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new tcb("get_point_defence_laser_pulsetime", new Class[]{}, (String) null));
          var1.b(param0 + -10274, new cva("set_point_defence_laser_pulsetime", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new wba("get_bomblet_spray_push_multiplier", new Class[]{}, (String) null));
          var1.b(-10258, new hia("set_bomblet_spray_push_multiplier", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new vtb("get_explosion_push_multiplier", new Class[]{}, (String) null));
          var1.b(param0 ^ -10242, new tba("set_explosion_push_multiplier", new Class[]{Integer.TYPE}, (String) null));
          var1.b(param0 ^ -10242, new qhb("get_ai_firing_range_upshift", new Class[]{}, (String) null));
          var1.b(param0 ^ -10242, new jt("set_ai_firing_range_upshift", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new db("get_world_width_upshift", new Class[]{}, (String) null));
          var1.b(-10258, new wmb("set_world_width_upshift", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new rob("get_weapon_particle_speed_downshift", new Class[]{}, (String) null));
          var1.b(-10258, new vs("set_weapon_particle_speed_downshift", new Class[]{Integer.TYPE}, (String) null));
          var1.b(param0 ^ -10242, new mi("get_weapon_projectile_speed_multiply", new Class[]{}, (String) null));
          var1.b(-10258, new nb("set_weapon_projectile_speed_multiply", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new bua("get_respawn_time", new Class[]{}, (String) null));
          var1.b(-10258, new hga("set_respawn_time", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new lpa("get_grappling_hook_max_length", new Class[]{}, (String) null));
          var1.b(-10258, new cqa("set_grappling_hook_max_length", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new nta("get_grappling_hook_min_length", new Class[]{}, (String) null));
          var1.b(param0 ^ -10242, new bp("set_grappling_hook_min_length", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new tra("get_grappling_hook_fire_force", new Class[]{}, (String) null));
          var1.b(-10258, new ep("set_grappling_hook_fire_force", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new tq("get_grappling_hook_spring_constant", new Class[]{}, (String) null));
          var1.b(-10258, new thb("set_grappling_hook_spring_constant", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new gta("get_grappling_hook_max_extension8_force", new Class[]{}, (String) null));
          var1.b(-10258, new qcb("set_grappling_hook_max_extension8_force", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new gca("get_grappling_hook_cooldown", new Class[]{}, (String) null));
          var1.b(-10258, new qa("set_grappling_hook_cooldown", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new saa("get_grappling_hook_rope_change_rate", new Class[]{}, (String) null));
          var1.b(-10258, new wob("set_grappling_hook_rope_change_rate", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new to("get_grappling_hook_rope_break_length", new Class[]{}, (String) null));
          var1.b(param0 + -10274, new wjb("set_grappling_hook_rope_break_length", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new jca("get_missiles_cooldown", new Class[]{}, (String) null));
          var1.b(-10258, new fna("set_missiles_cooldown", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new tkb("get_missiles_explosion_power", new Class[]{}, (String) null));
          var1.b(-10258, new eh("set_missiles_explosion_power", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new sua("get_missiles_acceleration", new Class[]{}, (String) null));
          var1.b(-10258, new bga("set_missiles_acceleration", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new nq("get_missiles_top_speed", new Class[]{}, (String) null));
          var1.b(-10258, new bnb("set_missiles_top_speed", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new bb("get_shields_toggle_cooldown", new Class[]{}, (String) null));
          var1.b(-10258, new afb("set_shields_toggle_cooldown", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new sm("get_shields_directional_idle_energy_usage", new Class[]{}, (String) null));
          var1.b(param0 + -10274, new oh("set_shields_directional_idle_energy_usage", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new m("get_shields_directional_radius", new Class[]{}, (String) null));
          var1.b(-10258, new np("set_shields_directional_radius", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new jta("get_shields_directional_arc", new Class[]{}, (String) null));
          var1.b(-10258, new geb("set_shields_directional_arc", new Class[]{Integer.TYPE}, (String) null));
          var1.b(param0 + -10274, new tha("get_shields_damage_energy_conversion", new Class[]{}, (String) null));
          var1.b(-10258, new lv("set_shields_damage_energy_conversion", new Class[]{Integer.TYPE}, (String) null));
          var1.b(param0 + -10274, new haa("get_repair_mode_cooldown", new Class[]{}, (String) null));
          var1.b(param0 + -10274, new ak("set_repair_mode_cooldown", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new ap("get_repair_mode_active_time", new Class[]{}, (String) null));
          var1.b(-10258, new vrb("set_repair_mode_active_time", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new ib("get_repair_mode_radius", new Class[]{}, (String) null));
          var1.b(param0 + -10274, new mg("set_repair_mode_radius", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new ldb("get_repair_mode_power", new Class[]{}, (String) null));
          var1.b(param0 ^ -10242, new ou("set_repair_mode_power", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new vob("get_boosters_cooldown", new Class[]{}, (String) null));
          var1.b(-10258, new pj("set_boosters_cooldown", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new cnb("get_boosters_active_time", new Class[]{}, (String) null));
          var1.b(-10258, new vd("set_boosters_active_time", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new tp("get_countermeasures_pulsetime", new Class[]{}, (String) null));
          var1.b(param0 ^ -10242, new hm("set_countermeasures_pulsetime", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new ikb("get_countermeasures_cooldown", new Class[]{}, (String) null));
          var1.b(-10258, new dia("set_countermeasures_cooldown", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new qtb("get_countermeasures_pulse_radius", new Class[]{}, (String) null));
          var1.b(-10258, new wl("set_countermeasures_pulse_radius", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new cea("get_self_destruct_prepare_toggle_cooldown", new Class[]{}, (String) null));
          var1.b(-10258, new pm("set_self_destruct_prepare_toggle_cooldown", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new td("get_self_destruct_activate_cooldown", new Class[]{}, (String) null));
          var1.b(param0 ^ -10242, new jq("set_self_destruct_activate_cooldown", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new rhb("get_self_destruct_timer", new Class[]{}, (String) null));
          var1.b(-10258, new flb("set_self_destruct_timer", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new ce("get_player_repair_time", new Class[]{}, (String) null));
          var1.b(param0 ^ -10242, new gh("set_player_repair_time", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new dca("get_player_repair_amount", new Class[]{}, (String) null));
          var1.b(-10258, new vj("set_player_repair_amount", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new kp("get_ai_repair_time", new Class[]{}, (String) null));
          var1.b(-10258, new jbb("set_ai_repair_time", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new g("get_ai_repair_amount", new Class[]{}, (String) null));
          var1.b(-10258, new oia("set_ai_repair_amount", new Class[]{Integer.TYPE}, (String) null));
          var1.b(param0 ^ -10242, new dbb("get_fighter_repair_time", new Class[]{}, (String) null));
          var1.b(param0 ^ -10242, new dsa("set_fighter_repair_time", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new fja("get_fighter_repair_amount", new Class[]{}, (String) null));
          var1.b(-10258, new tl("set_fighter_repair_amount", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new gu("get_ready_room_mission_time", new Class[]{}, (String) null));
          var1.b(param0 + -10274, new bq("set_ready_room_mission_time", new Class[]{Integer.TYPE}, (String) null));
          var1.b(-10258, new rfa("get_ready_room_mutator_time", new Class[]{}, (String) null));
          var1.b(-10258, new ah("set_ready_room_mutator_time", new Class[]{Integer.TYPE}, (String) null));
          var1.b(param0 ^ -10242, new iqa("get_ready_room_team_time", new Class[]{}, (String) null));
          var1.b(-10258, new nja("set_ready_room_team_time", new Class[]{Integer.TYPE}, (String) null));
          return var1;
        } else {
          return (ij) null;
        }
    }

    static {
        field_a = 16;
    }
}
