/*
 * Decompiled by CFR-JS 0.4.0.
 */
final class dq {
    static String[] field_a;
    private static String field_z;

    public static void a(int param0) {
        field_a = null;
        if (param0 != -19100) {
            field_a = null;
        }
    }

    static {
        $cfr$clinit();
    }

    private static void $cfr$clinit() {
        field_z = "dq.A(";
        field_a = new String[]{"ICON_WALK", "ICON_SPRINT", "ICON_TELEPORT", "ICON_LEVITATE", "", "", "", "", "", "", "ICON_HIT", "ICON_CONE", "ICON_SPLASH", "ICON_SHOVE", "ICON_SPEAR", "ICON_SWIPE", "ICON_CHARGE", "ICON_SHBARGE", "ICON_BUFFATTACK", "ICON_RANGE", "ICON_CURSPD", "ICON_SMASH", "ICON_JUMPSHV", "ICON_GUARD", "ICON_BUFFSPD", "ICON_FLKICK", "ICON_JUMP", "ICON_CRSATK", "", "", "ICON_RNGCONE", "ICON_POISON", "ICON_POKE", "ICON_HEAL", "ICON_EXTEND", "ICON_BUFFSPATK", "ICON_VAMPIRE", "ICON_RNGSPL", "ICON_FLSWIPE", "ICON_CRSSPATK", "ICON_SWAP", "ICON_PIT", "ICON_BLOCK", "ICON_CONFUSE", "ICON_PANIC", "", "", "", "", "", "ICON_PSVSPATK", "ICON_PSVSPD", "ICON_PSVATK", "ICON_PSVHP", "ICON_PSVSPL", "ICON_PSVRNG", "", "", "", "", "ICON_SNOW", "ICON_SUPERSPEED", "ICON_SLEEP", "ICON_SHIELD", "ICON_HAIL", "ICON_RAISE", "ICON_DBOMBER", "ICON_MARTYR", "ICON_INCOMING", "ICON_SPILTMILK", "ICON_DREAMS", "ICON_SLOWALL", "ICON_INSANOSAUCE", "ICON_SUPERSPEEDALL", "ICON_SHUFFLE", "ICON_FLOOD", "ICON_LEVITATE", "ICON_FULLHEAL", "ICON_INVINCIBLE", "ICON_CLAMS", "ICON_DISABLE", "ICON_FISHRAIN", "ICON_MASSPOISON", "ICON_ZOMBIES", "ICON_FLY", "ICON_TBOMBER", "ICON_STICKY", "ICON_FLIRT", "ICON_HMISSILE", "ICON_BANANARANG", "ICON_STAMPEDE", "ICON_MYSTERY", "ICON_SCAVENGER", "ICON_ATTACKUPALL", "ICON_SAUCEOFFLAME", "ICON_SPLIT", "ICON_CRANBERRY", "ICON_BUFFVENDOR", "ICON_HAZMAT", "ICON_BAGPIPE", "ICON_RESET", "ICON_PETATTACK", "ICON_TELEPORT_SP", "ICON_AIRSTRIKE", "ICON_PIZZAPARTY", "ICON_OHNO", "ICON_REFRESHING", "ICON_RAGE", "ICON_GASCLOUD", "ICON_ONE"};
    }
}
