/*
 * Decompiled by CFR-JS 0.4.0.
 */
final class sf {
    final static void a(int[] param0, int param1, int param2) {
        int incrementValue$0 = 0;
        int incrementValue$1 = 0;
        int incrementValue$2 = 0;
        int incrementValue$3 = 0;
        int incrementValue$4 = 0;
        int incrementValue$5 = 0;
        int incrementValue$6 = 0;
        int incrementValue$7 = 0;
        int incrementValue$8 = 0;
        param2 = param1 + param2 - 7;
        while (param1 < param2) {
            incrementValue$0 = param1;
            param1++;
            param0[incrementValue$0] = 0;
            incrementValue$1 = param1;
            param1++;
            param0[incrementValue$1] = 0;
            incrementValue$2 = param1;
            param1++;
            param0[incrementValue$2] = 0;
            incrementValue$3 = param1;
            param1++;
            param0[incrementValue$3] = 0;
            incrementValue$4 = param1;
            param1++;
            param0[incrementValue$4] = 0;
            incrementValue$5 = param1;
            param1++;
            param0[incrementValue$5] = 0;
            incrementValue$6 = param1;
            param1++;
            param0[incrementValue$6] = 0;
            incrementValue$7 = param1;
            param1++;
            param0[incrementValue$7] = 0;
        }
        param2 += 7;
        while (param1 < param2) {
            incrementValue$8 = param1;
            param1++;
            param0[incrementValue$8] = 0;
        }
    }

    final static void a(byte[] param0, int param1, byte[] param2, int param3, int param4) {
        int incrementValue$0 = 0;
        int incrementValue$1 = 0;
        int incrementValue$2 = 0;
        int incrementValue$3 = 0;
        int incrementValue$4 = 0;
        int incrementValue$5 = 0;
        int incrementValue$6 = 0;
        int incrementValue$7 = 0;
        int incrementValue$8 = 0;
        int incrementValue$9 = 0;
        int incrementValue$10 = 0;
        int incrementValue$11 = 0;
        int incrementValue$12 = 0;
        int incrementValue$13 = 0;
        int incrementValue$14 = 0;
        int incrementValue$15 = 0;
        int incrementValue$16 = 0;
        int incrementValue$17 = 0;
        int incrementValue$18 = 0;
        int incrementValue$19 = 0;
        int incrementValue$20 = 0;
        int incrementValue$21 = 0;
        int incrementValue$22 = 0;
        int incrementValue$23 = 0;
        int incrementValue$24 = 0;
        int incrementValue$25 = 0;
        int incrementValue$26 = 0;
        int incrementValue$27 = 0;
        int incrementValue$28 = 0;
        int incrementValue$29 = 0;
        int incrementValue$30 = 0;
        int incrementValue$31 = 0;
        int incrementValue$32 = 0;
        int incrementValue$33 = 0;
        int incrementValue$34 = 0;
        int incrementValue$35 = 0;
        int incrementValue$36 = 0;
        int incrementValue$37 = 0;
        int incrementValue$38 = 0;
        int incrementValue$39 = 0;
        int incrementValue$40 = 0;
        int incrementValue$41 = 0;
        int incrementValue$42 = 0;
        int incrementValue$43 = 0;
        int incrementValue$44 = 0;
        int incrementValue$45 = 0;
        int incrementValue$46 = 0;
        int incrementValue$47 = 0;
        int incrementValue$48 = 0;
        int incrementValue$49 = 0;
        int incrementValue$50 = 0;
        int incrementValue$51 = 0;
        int incrementValue$52 = 0;
        int incrementValue$53 = 0;
        int incrementValue$54 = 0;
        int incrementValue$55 = 0;
        int incrementValue$56 = 0;
        int incrementValue$57 = 0;
        int incrementValue$58 = 0;
        int incrementValue$59 = 0;
        int incrementValue$60 = 0;
        int incrementValue$61 = 0;
        int incrementValue$62 = 0;
        int incrementValue$63 = 0;
        int incrementValue$64 = 0;
        int incrementValue$65 = 0;
        int incrementValue$66 = 0;
        int incrementValue$67 = 0;
        int incrementValue$68 = 0;
        int incrementValue$69 = 0;
        int incrementValue$70 = 0;
        int incrementValue$71 = 0;
        if (param0 != param2) {
            param4 = param4 + param1;
            param4 -= 7;
            while (param1 < param4) {
                incrementValue$0 = param3;
                param3++;
                incrementValue$1 = param1;
                param1++;
                param2[incrementValue$0] = param0[incrementValue$1];
                incrementValue$2 = param3;
                param3++;
                incrementValue$3 = param1;
                param1++;
                param2[incrementValue$2] = param0[incrementValue$3];
                incrementValue$4 = param3;
                param3++;
                incrementValue$5 = param1;
                param1++;
                param2[incrementValue$4] = param0[incrementValue$5];
                incrementValue$6 = param3;
                param3++;
                incrementValue$7 = param1;
                param1++;
                param2[incrementValue$6] = param0[incrementValue$7];
                incrementValue$8 = param3;
                param3++;
                incrementValue$9 = param1;
                param1++;
                param2[incrementValue$8] = param0[incrementValue$9];
                incrementValue$10 = param3;
                param3++;
                incrementValue$11 = param1;
                param1++;
                param2[incrementValue$10] = param0[incrementValue$11];
                incrementValue$12 = param3;
                param3++;
                incrementValue$13 = param1;
                param1++;
                param2[incrementValue$12] = param0[incrementValue$13];
                incrementValue$14 = param3;
                param3++;
                incrementValue$15 = param1;
                param1++;
                param2[incrementValue$14] = param0[incrementValue$15];
            }
            param4 += 7;
            while (param1 < param4) {
                incrementValue$16 = param3;
                param3++;
                incrementValue$17 = param1;
                param1++;
                param2[incrementValue$16] = param0[incrementValue$17];
            }
            return;
        }
        if (param1 == param3) {
            return;
        }
        if (param3 <= param1) {
            param4 = param4 + param1;
            param4 -= 7;
            while (param1 < param4) {
                incrementValue$18 = param3;
                param3++;
                incrementValue$19 = param1;
                param1++;
                param2[incrementValue$18] = param0[incrementValue$19];
                incrementValue$20 = param3;
                param3++;
                incrementValue$21 = param1;
                param1++;
                param2[incrementValue$20] = param0[incrementValue$21];
                incrementValue$22 = param3;
                param3++;
                incrementValue$23 = param1;
                param1++;
                param2[incrementValue$22] = param0[incrementValue$23];
                incrementValue$24 = param3;
                param3++;
                incrementValue$25 = param1;
                param1++;
                param2[incrementValue$24] = param0[incrementValue$25];
                incrementValue$26 = param3;
                param3++;
                incrementValue$27 = param1;
                param1++;
                param2[incrementValue$26] = param0[incrementValue$27];
                incrementValue$28 = param3;
                param3++;
                incrementValue$29 = param1;
                param1++;
                param2[incrementValue$28] = param0[incrementValue$29];
                incrementValue$30 = param3;
                param3++;
                incrementValue$31 = param1;
                param1++;
                param2[incrementValue$30] = param0[incrementValue$31];
                incrementValue$32 = param3;
                param3++;
                incrementValue$33 = param1;
                param1++;
                param2[incrementValue$32] = param0[incrementValue$33];
            }
            param4 += 7;
            while (param1 < param4) {
                incrementValue$34 = param3;
                param3++;
                incrementValue$35 = param1;
                param1++;
                param2[incrementValue$34] = param0[incrementValue$35];
            }
            return;
        }
        if (param3 >= param1 + param4) {
            param4 = param4 + param1;
            param4 -= 7;
            while (param1 < param4) {
                incrementValue$36 = param3;
                param3++;
                incrementValue$37 = param1;
                param1++;
                param2[incrementValue$36] = param0[incrementValue$37];
                incrementValue$38 = param3;
                param3++;
                incrementValue$39 = param1;
                param1++;
                param2[incrementValue$38] = param0[incrementValue$39];
                incrementValue$40 = param3;
                param3++;
                incrementValue$41 = param1;
                param1++;
                param2[incrementValue$40] = param0[incrementValue$41];
                incrementValue$42 = param3;
                param3++;
                incrementValue$43 = param1;
                param1++;
                param2[incrementValue$42] = param0[incrementValue$43];
                incrementValue$44 = param3;
                param3++;
                incrementValue$45 = param1;
                param1++;
                param2[incrementValue$44] = param0[incrementValue$45];
                incrementValue$46 = param3;
                param3++;
                incrementValue$47 = param1;
                param1++;
                param2[incrementValue$46] = param0[incrementValue$47];
                incrementValue$48 = param3;
                param3++;
                incrementValue$49 = param1;
                param1++;
                param2[incrementValue$48] = param0[incrementValue$49];
                incrementValue$50 = param3;
                param3++;
                incrementValue$51 = param1;
                param1++;
                param2[incrementValue$50] = param0[incrementValue$51];
            }
            param4 += 7;
            while (param1 < param4) {
                incrementValue$52 = param3;
                param3++;
                incrementValue$53 = param1;
                param1++;
                param2[incrementValue$52] = param0[incrementValue$53];
            }
            return;
        }
        param4--;
        param1 = param1 + param4;
        param3 = param3 + param4;
        param4 = param1 - param4;
        param4 += 7;
        while (param1 >= param4) {
            incrementValue$54 = param3;
            param3--;
            incrementValue$55 = param1;
            param1--;
            param2[incrementValue$54] = param0[incrementValue$55];
            incrementValue$56 = param3;
            param3--;
            incrementValue$57 = param1;
            param1--;
            param2[incrementValue$56] = param0[incrementValue$57];
            incrementValue$58 = param3;
            param3--;
            incrementValue$59 = param1;
            param1--;
            param2[incrementValue$58] = param0[incrementValue$59];
            incrementValue$60 = param3;
            param3--;
            incrementValue$61 = param1;
            param1--;
            param2[incrementValue$60] = param0[incrementValue$61];
            incrementValue$62 = param3;
            param3--;
            incrementValue$63 = param1;
            param1--;
            param2[incrementValue$62] = param0[incrementValue$63];
            incrementValue$64 = param3;
            param3--;
            incrementValue$65 = param1;
            param1--;
            param2[incrementValue$64] = param0[incrementValue$65];
            incrementValue$66 = param3;
            param3--;
            incrementValue$67 = param1;
            param1--;
            param2[incrementValue$66] = param0[incrementValue$67];
            incrementValue$68 = param3;
            param3--;
            incrementValue$69 = param1;
            param1--;
            param2[incrementValue$68] = param0[incrementValue$69];
        }
        param4 -= 7;
        while (param1 >= param4) {
            incrementValue$70 = param3;
            param3--;
            incrementValue$71 = param1;
            param1--;
            param2[incrementValue$70] = param0[incrementValue$71];
        }
    }

    final static void a(int[] param0, int param1, int[] param2, int param3, int param4) {
        int incrementValue$0 = 0;
        int incrementValue$1 = 0;
        int incrementValue$2 = 0;
        int incrementValue$3 = 0;
        int incrementValue$4 = 0;
        int incrementValue$5 = 0;
        int incrementValue$6 = 0;
        int incrementValue$7 = 0;
        int incrementValue$8 = 0;
        int incrementValue$9 = 0;
        int incrementValue$10 = 0;
        int incrementValue$11 = 0;
        int incrementValue$12 = 0;
        int incrementValue$13 = 0;
        int incrementValue$14 = 0;
        int incrementValue$15 = 0;
        int incrementValue$16 = 0;
        int incrementValue$17 = 0;
        int incrementValue$18 = 0;
        int incrementValue$19 = 0;
        int incrementValue$20 = 0;
        int incrementValue$21 = 0;
        int incrementValue$22 = 0;
        int incrementValue$23 = 0;
        int incrementValue$24 = 0;
        int incrementValue$25 = 0;
        int incrementValue$26 = 0;
        int incrementValue$27 = 0;
        int incrementValue$28 = 0;
        int incrementValue$29 = 0;
        int incrementValue$30 = 0;
        int incrementValue$31 = 0;
        int incrementValue$32 = 0;
        int incrementValue$33 = 0;
        int incrementValue$34 = 0;
        int incrementValue$35 = 0;
        int incrementValue$36 = 0;
        int incrementValue$37 = 0;
        int incrementValue$38 = 0;
        int incrementValue$39 = 0;
        int incrementValue$40 = 0;
        int incrementValue$41 = 0;
        int incrementValue$42 = 0;
        int incrementValue$43 = 0;
        int incrementValue$44 = 0;
        int incrementValue$45 = 0;
        int incrementValue$46 = 0;
        int incrementValue$47 = 0;
        int incrementValue$48 = 0;
        int incrementValue$49 = 0;
        int incrementValue$50 = 0;
        int incrementValue$51 = 0;
        int incrementValue$52 = 0;
        int incrementValue$53 = 0;
        int incrementValue$54 = 0;
        int incrementValue$55 = 0;
        int incrementValue$56 = 0;
        int incrementValue$57 = 0;
        int incrementValue$58 = 0;
        int incrementValue$59 = 0;
        int incrementValue$60 = 0;
        int incrementValue$61 = 0;
        int incrementValue$62 = 0;
        int incrementValue$63 = 0;
        int incrementValue$64 = 0;
        int incrementValue$65 = 0;
        int incrementValue$66 = 0;
        int incrementValue$67 = 0;
        int incrementValue$68 = 0;
        int incrementValue$69 = 0;
        int incrementValue$70 = 0;
        int incrementValue$71 = 0;
        if (param0 != param2) {
            param4 = param4 + param1;
            param4 -= 7;
            while (param1 < param4) {
                incrementValue$0 = param3;
                param3++;
                incrementValue$1 = param1;
                param1++;
                param2[incrementValue$0] = param0[incrementValue$1];
                incrementValue$2 = param3;
                param3++;
                incrementValue$3 = param1;
                param1++;
                param2[incrementValue$2] = param0[incrementValue$3];
                incrementValue$4 = param3;
                param3++;
                incrementValue$5 = param1;
                param1++;
                param2[incrementValue$4] = param0[incrementValue$5];
                incrementValue$6 = param3;
                param3++;
                incrementValue$7 = param1;
                param1++;
                param2[incrementValue$6] = param0[incrementValue$7];
                incrementValue$8 = param3;
                param3++;
                incrementValue$9 = param1;
                param1++;
                param2[incrementValue$8] = param0[incrementValue$9];
                incrementValue$10 = param3;
                param3++;
                incrementValue$11 = param1;
                param1++;
                param2[incrementValue$10] = param0[incrementValue$11];
                incrementValue$12 = param3;
                param3++;
                incrementValue$13 = param1;
                param1++;
                param2[incrementValue$12] = param0[incrementValue$13];
                incrementValue$14 = param3;
                param3++;
                incrementValue$15 = param1;
                param1++;
                param2[incrementValue$14] = param0[incrementValue$15];
            }
            param4 += 7;
            while (param1 < param4) {
                incrementValue$16 = param3;
                param3++;
                incrementValue$17 = param1;
                param1++;
                param2[incrementValue$16] = param0[incrementValue$17];
            }
            return;
        }
        if (param1 == param3) {
            return;
        }
        if (param3 <= param1) {
            param4 = param4 + param1;
            param4 -= 7;
            while (param1 < param4) {
                incrementValue$18 = param3;
                param3++;
                incrementValue$19 = param1;
                param1++;
                param2[incrementValue$18] = param0[incrementValue$19];
                incrementValue$20 = param3;
                param3++;
                incrementValue$21 = param1;
                param1++;
                param2[incrementValue$20] = param0[incrementValue$21];
                incrementValue$22 = param3;
                param3++;
                incrementValue$23 = param1;
                param1++;
                param2[incrementValue$22] = param0[incrementValue$23];
                incrementValue$24 = param3;
                param3++;
                incrementValue$25 = param1;
                param1++;
                param2[incrementValue$24] = param0[incrementValue$25];
                incrementValue$26 = param3;
                param3++;
                incrementValue$27 = param1;
                param1++;
                param2[incrementValue$26] = param0[incrementValue$27];
                incrementValue$28 = param3;
                param3++;
                incrementValue$29 = param1;
                param1++;
                param2[incrementValue$28] = param0[incrementValue$29];
                incrementValue$30 = param3;
                param3++;
                incrementValue$31 = param1;
                param1++;
                param2[incrementValue$30] = param0[incrementValue$31];
                incrementValue$32 = param3;
                param3++;
                incrementValue$33 = param1;
                param1++;
                param2[incrementValue$32] = param0[incrementValue$33];
            }
            param4 += 7;
            while (param1 < param4) {
                incrementValue$34 = param3;
                param3++;
                incrementValue$35 = param1;
                param1++;
                param2[incrementValue$34] = param0[incrementValue$35];
            }
            return;
        }
        if (param3 >= param1 + param4) {
            param4 = param4 + param1;
            param4 -= 7;
            while (param1 < param4) {
                incrementValue$36 = param3;
                param3++;
                incrementValue$37 = param1;
                param1++;
                param2[incrementValue$36] = param0[incrementValue$37];
                incrementValue$38 = param3;
                param3++;
                incrementValue$39 = param1;
                param1++;
                param2[incrementValue$38] = param0[incrementValue$39];
                incrementValue$40 = param3;
                param3++;
                incrementValue$41 = param1;
                param1++;
                param2[incrementValue$40] = param0[incrementValue$41];
                incrementValue$42 = param3;
                param3++;
                incrementValue$43 = param1;
                param1++;
                param2[incrementValue$42] = param0[incrementValue$43];
                incrementValue$44 = param3;
                param3++;
                incrementValue$45 = param1;
                param1++;
                param2[incrementValue$44] = param0[incrementValue$45];
                incrementValue$46 = param3;
                param3++;
                incrementValue$47 = param1;
                param1++;
                param2[incrementValue$46] = param0[incrementValue$47];
                incrementValue$48 = param3;
                param3++;
                incrementValue$49 = param1;
                param1++;
                param2[incrementValue$48] = param0[incrementValue$49];
                incrementValue$50 = param3;
                param3++;
                incrementValue$51 = param1;
                param1++;
                param2[incrementValue$50] = param0[incrementValue$51];
            }
            param4 += 7;
            while (param1 < param4) {
                incrementValue$52 = param3;
                param3++;
                incrementValue$53 = param1;
                param1++;
                param2[incrementValue$52] = param0[incrementValue$53];
            }
            return;
        }
        param4--;
        param1 = param1 + param4;
        param3 = param3 + param4;
        param4 = param1 - param4;
        param4 += 7;
        while (param1 >= param4) {
            incrementValue$54 = param3;
            param3--;
            incrementValue$55 = param1;
            param1--;
            param2[incrementValue$54] = param0[incrementValue$55];
            incrementValue$56 = param3;
            param3--;
            incrementValue$57 = param1;
            param1--;
            param2[incrementValue$56] = param0[incrementValue$57];
            incrementValue$58 = param3;
            param3--;
            incrementValue$59 = param1;
            param1--;
            param2[incrementValue$58] = param0[incrementValue$59];
            incrementValue$60 = param3;
            param3--;
            incrementValue$61 = param1;
            param1--;
            param2[incrementValue$60] = param0[incrementValue$61];
            incrementValue$62 = param3;
            param3--;
            incrementValue$63 = param1;
            param1--;
            param2[incrementValue$62] = param0[incrementValue$63];
            incrementValue$64 = param3;
            param3--;
            incrementValue$65 = param1;
            param1--;
            param2[incrementValue$64] = param0[incrementValue$65];
            incrementValue$66 = param3;
            param3--;
            incrementValue$67 = param1;
            param1--;
            param2[incrementValue$66] = param0[incrementValue$67];
            incrementValue$68 = param3;
            param3--;
            incrementValue$69 = param1;
            param1--;
            param2[incrementValue$68] = param0[incrementValue$69];
        }
        param4 -= 7;
        while (param1 >= param4) {
            incrementValue$70 = param3;
            param3--;
            incrementValue$71 = param1;
            param1--;
            param2[incrementValue$70] = param0[incrementValue$71];
        }
    }

    final static void a(Object[] param0, int param1, Object[] param2, int param3, int param4) {
        int incrementValue$0 = 0;
        int incrementValue$1 = 0;
        int incrementValue$2 = 0;
        int incrementValue$3 = 0;
        int incrementValue$4 = 0;
        int incrementValue$5 = 0;
        int incrementValue$6 = 0;
        int incrementValue$7 = 0;
        int incrementValue$8 = 0;
        int incrementValue$9 = 0;
        int incrementValue$10 = 0;
        int incrementValue$11 = 0;
        int incrementValue$12 = 0;
        int incrementValue$13 = 0;
        int incrementValue$14 = 0;
        int incrementValue$15 = 0;
        int incrementValue$16 = 0;
        int incrementValue$17 = 0;
        int incrementValue$18 = 0;
        int incrementValue$19 = 0;
        int incrementValue$20 = 0;
        int incrementValue$21 = 0;
        int incrementValue$22 = 0;
        int incrementValue$23 = 0;
        int incrementValue$24 = 0;
        int incrementValue$25 = 0;
        int incrementValue$26 = 0;
        int incrementValue$27 = 0;
        int incrementValue$28 = 0;
        int incrementValue$29 = 0;
        int incrementValue$30 = 0;
        int incrementValue$31 = 0;
        int incrementValue$32 = 0;
        int incrementValue$33 = 0;
        int incrementValue$34 = 0;
        int incrementValue$35 = 0;
        int incrementValue$36 = 0;
        int incrementValue$37 = 0;
        int incrementValue$38 = 0;
        int incrementValue$39 = 0;
        int incrementValue$40 = 0;
        int incrementValue$41 = 0;
        int incrementValue$42 = 0;
        int incrementValue$43 = 0;
        int incrementValue$44 = 0;
        int incrementValue$45 = 0;
        int incrementValue$46 = 0;
        int incrementValue$47 = 0;
        int incrementValue$48 = 0;
        int incrementValue$49 = 0;
        int incrementValue$50 = 0;
        int incrementValue$51 = 0;
        int incrementValue$52 = 0;
        int incrementValue$53 = 0;
        int incrementValue$54 = 0;
        int incrementValue$55 = 0;
        int incrementValue$56 = 0;
        int incrementValue$57 = 0;
        int incrementValue$58 = 0;
        int incrementValue$59 = 0;
        int incrementValue$60 = 0;
        int incrementValue$61 = 0;
        int incrementValue$62 = 0;
        int incrementValue$63 = 0;
        int incrementValue$64 = 0;
        int incrementValue$65 = 0;
        int incrementValue$66 = 0;
        int incrementValue$67 = 0;
        int incrementValue$68 = 0;
        int incrementValue$69 = 0;
        int incrementValue$70 = 0;
        int incrementValue$71 = 0;
        if (param0 != param2) {
            param4 = param4 + param1;
            param4 -= 7;
            while (param1 < param4) {
                incrementValue$0 = param3;
                param3++;
                incrementValue$1 = param1;
                param1++;
                param2[incrementValue$0] = param0[incrementValue$1];
                incrementValue$2 = param3;
                param3++;
                incrementValue$3 = param1;
                param1++;
                param2[incrementValue$2] = param0[incrementValue$3];
                incrementValue$4 = param3;
                param3++;
                incrementValue$5 = param1;
                param1++;
                param2[incrementValue$4] = param0[incrementValue$5];
                incrementValue$6 = param3;
                param3++;
                incrementValue$7 = param1;
                param1++;
                param2[incrementValue$6] = param0[incrementValue$7];
                incrementValue$8 = param3;
                param3++;
                incrementValue$9 = param1;
                param1++;
                param2[incrementValue$8] = param0[incrementValue$9];
                incrementValue$10 = param3;
                param3++;
                incrementValue$11 = param1;
                param1++;
                param2[incrementValue$10] = param0[incrementValue$11];
                incrementValue$12 = param3;
                param3++;
                incrementValue$13 = param1;
                param1++;
                param2[incrementValue$12] = param0[incrementValue$13];
                incrementValue$14 = param3;
                param3++;
                incrementValue$15 = param1;
                param1++;
                param2[incrementValue$14] = param0[incrementValue$15];
            }
            param4 += 7;
            while (param1 < param4) {
                incrementValue$16 = param3;
                param3++;
                incrementValue$17 = param1;
                param1++;
                param2[incrementValue$16] = param0[incrementValue$17];
            }
            return;
        }
        if (param1 == param3) {
            return;
        }
        if (param3 <= param1) {
            param4 = param4 + param1;
            param4 -= 7;
            while (param1 < param4) {
                incrementValue$18 = param3;
                param3++;
                incrementValue$19 = param1;
                param1++;
                param2[incrementValue$18] = param0[incrementValue$19];
                incrementValue$20 = param3;
                param3++;
                incrementValue$21 = param1;
                param1++;
                param2[incrementValue$20] = param0[incrementValue$21];
                incrementValue$22 = param3;
                param3++;
                incrementValue$23 = param1;
                param1++;
                param2[incrementValue$22] = param0[incrementValue$23];
                incrementValue$24 = param3;
                param3++;
                incrementValue$25 = param1;
                param1++;
                param2[incrementValue$24] = param0[incrementValue$25];
                incrementValue$26 = param3;
                param3++;
                incrementValue$27 = param1;
                param1++;
                param2[incrementValue$26] = param0[incrementValue$27];
                incrementValue$28 = param3;
                param3++;
                incrementValue$29 = param1;
                param1++;
                param2[incrementValue$28] = param0[incrementValue$29];
                incrementValue$30 = param3;
                param3++;
                incrementValue$31 = param1;
                param1++;
                param2[incrementValue$30] = param0[incrementValue$31];
                incrementValue$32 = param3;
                param3++;
                incrementValue$33 = param1;
                param1++;
                param2[incrementValue$32] = param0[incrementValue$33];
            }
            param4 += 7;
            while (param1 < param4) {
                incrementValue$34 = param3;
                param3++;
                incrementValue$35 = param1;
                param1++;
                param2[incrementValue$34] = param0[incrementValue$35];
            }
            return;
        }
        if (param3 >= param1 + param4) {
            param4 = param4 + param1;
            param4 -= 7;
            while (param1 < param4) {
                incrementValue$36 = param3;
                param3++;
                incrementValue$37 = param1;
                param1++;
                param2[incrementValue$36] = param0[incrementValue$37];
                incrementValue$38 = param3;
                param3++;
                incrementValue$39 = param1;
                param1++;
                param2[incrementValue$38] = param0[incrementValue$39];
                incrementValue$40 = param3;
                param3++;
                incrementValue$41 = param1;
                param1++;
                param2[incrementValue$40] = param0[incrementValue$41];
                incrementValue$42 = param3;
                param3++;
                incrementValue$43 = param1;
                param1++;
                param2[incrementValue$42] = param0[incrementValue$43];
                incrementValue$44 = param3;
                param3++;
                incrementValue$45 = param1;
                param1++;
                param2[incrementValue$44] = param0[incrementValue$45];
                incrementValue$46 = param3;
                param3++;
                incrementValue$47 = param1;
                param1++;
                param2[incrementValue$46] = param0[incrementValue$47];
                incrementValue$48 = param3;
                param3++;
                incrementValue$49 = param1;
                param1++;
                param2[incrementValue$48] = param0[incrementValue$49];
                incrementValue$50 = param3;
                param3++;
                incrementValue$51 = param1;
                param1++;
                param2[incrementValue$50] = param0[incrementValue$51];
            }
            param4 += 7;
            while (param1 < param4) {
                incrementValue$52 = param3;
                param3++;
                incrementValue$53 = param1;
                param1++;
                param2[incrementValue$52] = param0[incrementValue$53];
            }
            return;
        }
        param4--;
        param1 = param1 + param4;
        param3 = param3 + param4;
        param4 = param1 - param4;
        param4 += 7;
        while (param1 >= param4) {
            incrementValue$54 = param3;
            param3--;
            incrementValue$55 = param1;
            param1--;
            param2[incrementValue$54] = param0[incrementValue$55];
            incrementValue$56 = param3;
            param3--;
            incrementValue$57 = param1;
            param1--;
            param2[incrementValue$56] = param0[incrementValue$57];
            incrementValue$58 = param3;
            param3--;
            incrementValue$59 = param1;
            param1--;
            param2[incrementValue$58] = param0[incrementValue$59];
            incrementValue$60 = param3;
            param3--;
            incrementValue$61 = param1;
            param1--;
            param2[incrementValue$60] = param0[incrementValue$61];
            incrementValue$62 = param3;
            param3--;
            incrementValue$63 = param1;
            param1--;
            param2[incrementValue$62] = param0[incrementValue$63];
            incrementValue$64 = param3;
            param3--;
            incrementValue$65 = param1;
            param1--;
            param2[incrementValue$64] = param0[incrementValue$65];
            incrementValue$66 = param3;
            param3--;
            incrementValue$67 = param1;
            param1--;
            param2[incrementValue$66] = param0[incrementValue$67];
            incrementValue$68 = param3;
            param3--;
            incrementValue$69 = param1;
            param1--;
            param2[incrementValue$68] = param0[incrementValue$69];
        }
        param4 -= 7;
        while (param1 >= param4) {
            incrementValue$70 = param3;
            param3--;
            incrementValue$71 = param1;
            param1--;
            param2[incrementValue$70] = param0[incrementValue$71];
        }
    }
}
